# Generated by Django 3.2.25 on 2025-02-17 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='country',
            field=models.CharField(default='UK', max_length=40),
            preserve_default=False,
        ),
    ]
