# Generated by Django 5.1.6 on 2025-02-25 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='mission',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
